name: cli

on:
  workflow_call:
    inputs:
      args:
        required: true
        type: string
    secrets:
      QIITA_ACCESS_TOKEN:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: go.mod
      - run: go run . ${{ inputs.args }}
        env:
          QIITA_ACCESS_TOKEN: ${{ secrets.QIITA_ACCESS_TOKEN }}
