name: cli

on:
  workflow_call:
    inputs:
      args:
        required: true
        type: string
    secrets:
      QIITA_ACCESS_TOKEN:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639 # v4.2.1
        with:
          go-version-file: go.mod
      - run: go run . ${{ inputs.args }}
        env:
          QIITA_ACCESS_TOKEN: ${{ secrets.QIITA_ACCESS_TOKEN }}
