name: likes weekly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # 毎日 12:00
    - cron: "0 15 * * *" # 毎日 00:00

jobs:
  daily:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.schedule == '0 15 * * *' }}
    uses: ./.github/workflows/_cli.yml
    secrets: inherit
    with:
      args: likes daily

  weekly:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.schedule == '0 15 * * *' }}
    uses: ./.github/workflows/_cli.yml
    secrets: inherit
    with:
      args: likes weekly
